on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: nix-builder

jobs:
  run-x86_64-linux:
    name: nix builder for Ubuntu
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Run `nix-build default.nix`
      run: |
        nix-build default.nix

    - name: Quarto check
      run: |
        nix-shell default.nix

#  run-x86_64-darwin:
#    name: nix builder for MacOS X86_64
#    # the DeterminateSystems action currently uses macos-12
#    # https://github.com/DeterminateSystems/nix-installer-action/blob/main/.github/workflows/ci.yml
#    runs-on: macos-12
#    steps:
#    - uses: actions/checkout@v3
#    - name: Install Nix
#      uses: DeterminateSystems/nix-installer-action@main
#    - name: Run `nix-build default.nix`
#      run: |
#        nix-build default.nix
        
    - name: Quarto check
      run: |
        nix-shell default.nix
    
    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: '["hello.html", "hello_typst.pdf"]'
        push: true
        default_author: github_actions
        message: 'Update reports'
